name: terraform apply -destroy

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      working-directory:
        description: The working directory for Terraform commands
        type: string
        required: false
        default: ./terra

      environment:
        description: The environment to plan (e.g., dev, staging, prod)
        type: string
        required: true

      TF_CLI_ARGS_init:
        description: Additional options to pass to 'terraform init'
        type: string
        required: false
        default: ""

      workspace:
        description: Switch to the workspace matching the environment before running 'terraform plan'
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_apply:
        description: Additional options to pass to 'terraform apply'
        type: string
        required: false
        default: ""

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      working-directory:
        description: The working directory for Terraform commands
        type: string
        required: false
        default: ./terra

      environment:
        description: The environment to apply (e.g., dev, staging, prod)
        type: string
        required: true

      TF_CLI_ARGS_init:
        description: Additional options to pass to 'terraform init'
        type: string
        required: false
        default: ""

      workspace:
        description: Switch to the workspace matching the environment before running 'terraform plan'
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_apply:
        description: Additional options to pass to 'terraform apply'
        type: string
        required: false
        default: ""

jobs:
  apply:
    name: apply
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_WOKSPACE: ${{ inputs.environment }}
      TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_apply: ${{ inputs.TF_CLI_ARGS_apply }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        # with: TODO

      - uses: percebus/github-actions-terraform/.github/actions/setup@main
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - name: terraform workspace select ${{ inputs.environment }}
        if: ${{ inputs.workspace }}
        working-directory: ${{ inputs.working-directory }}
        run: terraform workspace select ${{ inputs.environment }} || terraform workspace new ${{ inputs.environment }}

      # TODO move to common
      - uses: actions/download-artifact@v5
        with:
          name: tfplan_destroy
          path: ${{ inputs.working-directory }}/dist

      - uses: percebus/github-actions-terraform/.github/actions/apply@main
        with:
          working-directory: ${{ inputs.working-directory }}
          TF_CLI_ARGS_apply: -input=false dist/destroy.tfplan

      # TODO add post-apply plan to detect drift and/or issues with the apply
