# TODO? merge w/ test_workflows__apply.yml
name: Deployment

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: Target environment
        type: choice
        required: false
        options:
          - ci_branch
          - ci_main
          - dev
          - prod
        default: ci_main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - name: Set STACK_ID
        id: set-id
        run: |
          echo "STACK_ID=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
    outputs:
      STACK_ID: ${{ steps.set-id.outputs.STACK_ID }}

  terraform_plan:
    name: terraform
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ github.ref_name == 'main' && inputs.environment || 'ci_branch' }}_plan
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"

  terraform_apply_plan:
    name: terraform
    needs: terraform_plan
    uses: ./.github/workflows/apply.yml
    with:
      environment: ${{ github.ref_name == 'main' && inputs.environment || 'ci_branch' }}
