name: Deployment

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: Target environment
        type: choice
        required: false
        options:
          - ci_main
          - ci_branch
          - dev
          - prod
        default: ci_main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main

      # TODO move to github-actions-common or -git
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "STACK_ID=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          else
            echo "environment=ci_branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}
      environment: ${{ steps.set_variables.outputs.environment }}

  terraform_plan:
    name: terraform
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}_plan
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"

  terraform_apply_plan:
    name: terraform
    needs:
      - terraform_plan
      - setup
    uses: ./.github/workflows/apply.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}
