name: terraform plan

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      working-directory:
        description: The working directory for Terraform commands
        type: string
        required: false
        default: ./terra

      environment:
        description: The environment to plan (e.g., dev, staging, prod)
        type: string
        required: true

      TF_CLI_ARGS_plan:
        description: Additional options to pass to 'terraform plan'
        type: string
        required: false
        default: ""

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      working-directory:
        description: The working directory for Terraform commands
        type: string
        required: false
        default: ./terra

      environment:
        description: The environment to plan (e.g., dev, staging, prod)
        type: string
        required: true

      TF_CLI_ARGS_plan:
        description: Additional options to pass to 'terraform plan'
        type: string
        required: false
        default: ""

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=ci_main" >> $GITHUB_OUTPUT
          else
            echo "environment=ci_branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      environment: ${{ steps.set_variables.outputs.environment }}

  plan:
    name: plan
    needs: setup
    runs-on: ubuntu-latest
    environment: ${{ steps.set_variables.outputs.environment }}
    env:
      TF_CLI_ARGS_plan: "-var-file=./env/${{ steps.set_variables.outputs.environment }}.tfvars ${{ inputs.TF_CLI_ARGS_plan }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        # with: TODO

      - uses: percebus/github-actions-terraform/.github/actions/setup@main

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/validate@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/plan@main
        with:
          working-directory: ${{ inputs.working-directory }}

      # TODO move to common
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.working-directory }}/dist
          name: dist
          if-no-files-found: error
