name: terraform plan -destroy

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      #   GITHUB_TOKEN:
      #     description: GitHub token for API access (e.g., commenting on PRs)
      #     required: false

      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      name:
        description: The name of the step
        type: string
        required: false
        default: plan -destroy

      environment:
        description: The environment to plan (e.g., dev, staging, prod)
        type: string
        required: true

      working-directory:
        description: The working directory for Terraform commands
        type: string
        required: false
        default: ./terra

      backend_override:
        description: Rename backend_override.tf.example to backend_override.tf before running 'terraform init'
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: Additional options to pass to 'terraform init'
        type: string
        required: false
        default: ""

      TF_CLI_ARGS_plan:
        description: Additional options to pass to 'terraform plan'
        type: string
        required: false
        default: ""

# NOTE: Targetting job sets these
# permissions:
#   contents: read
#   actions: read
#   pull-requests: write

jobs:
  plan:
    name: ${{ inputs.name }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_WORKSPACE: ${{ vars.ENVIRONMENT }}
      TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars ${{ inputs.TF_CLI_ARGS_plan }}"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        # with: TODO

      - uses: percebus/github-actions-terraform/.github/actions/setup@main
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          backend_override: ${{ inputs.backend_override }}

      # TODO? add a flag to skip validate in case of destroy? or just run it as is?
      - uses: percebus/github-actions-terraform/.github/actions/validate@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/plan@main
        with:
          github_token: ${{ github.token }}
          working-directory: ${{ inputs.working-directory }}

          # TODO
          # tfplan_path: dist/destroy.tfplan
          # TF_CLI_ARGS_plan: "-destroy"

          # XXX
          TF_CLI_ARGS_plan: "-destroy -out=dist/destroy.tfplan"

      # TODO move to common
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.working-directory }}/dist
          name: tfplan_destroy
          if-no-files-found: error
          overwrite: true
