name: terraform plan

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    secrets:
      TF_API_TOKEN:
        description: Terraform Cloud API token
        required: false

    inputs:
      environment:
        description: environment
        type: string
        required: true

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      backend_override:
        description: backend_override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      validate:
        description: validate
        type: boolean
        required: false
        default: true

      destroy:
        description: destroy
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      environment:
        description: environment
        type: string
        required: true

      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      backend_override:
        description: backend_override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: "-input=false"

      validate:
        description: validate
        type: boolean
        required: false
        default: true

      destroy:
        description: destroy
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_plan:
        description: TF_CLI_ARGS_plan
        type: string
        required: false
        default: ""

env:
  terraform_action: ${{ inputs.destroy && 'destroy' || 'update' }}
  TF_IN_AUTOMATION: true
  TF_CLI_ARGS_plan: ${{ inputs.destroy && '-destroy' || '' }}

# NOTE: Targetting job sets these
# permissions:
#   contents: read
#   actions: read
#   pull-requests: write

jobs:
  plan:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      TF_WORKSPACE: ${{ vars.ENVIRONMENT }}
    name: plan ${{ vars.TF_CLI_ARGS_plan }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        # with: TODO

      - uses: percebus/github-actions-terraform/.github/actions/setup@main
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          backend_override: ${{ inputs.backend_override }}
          TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}

      - uses: percebus/github-actions-terraform/.github/actions/validate@main
        if: ${{ inputs.validate }}
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/plan@main
        with:
          github_token: ${{ github.token }}
          working-directory: ${{ inputs.working-directory }}
          header: üóëÔ∏è `terraform plan ${{ env.TF_CLI_ARGS_plan }}`
          tfplan_path: dist/${{ env.terraform_action }}.tfplan
          TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars ${{ inputs.TF_CLI_ARGS_plan }}"

      # TODO move to common
      - uses: actions/upload-artifact@v4
        with:
          path: ${{ inputs.working-directory }}/dist
          name: tfplan_${{ env.terraform_action }}
          if-no-files-found: error
          overwrite: true
