name: "Test actions/test"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Cancelling an apply might corrupt the state.
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: read

jobs:
  terraform_test:
    name: terraform test
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          backend_override: true

      - uses: ./.github/actions/test
