name: "Test worfklows/fmt-check"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Apparently terraform init does NOT create a lock.
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  TF_CLI_ARGS_init: -reconfigure

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "TF_CLI_ARGS_init=-reconfigure" >> $GITHUB_OUTPUT
    outputs:
      TF_CLI_ARGS_init: ${{ steps.set_variables.outputs.TF_CLI_ARGS_init }}

  default:
    name: terraform
    needs: setup
    uses: ./.github/workflows/validate.yml
    with:
      backend_override: true
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}

  working-directory__matrix:
    needs:
      - default
      - setup

    strategy:
      matrix:
        path:
          # - ./terra # already tested by default
          - ./assets/terra

    name: terraform -chdir=.../${{ matrix.path }}
    uses: ./.github/workflows/fmt-check.yml
    with:
      working-directory: ${{ matrix.path }}
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
