name: "Test worfklows/plan"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # NOTE: Cancelling a plan might corrupt the state.
  cancel-in-progress: false

permissions:
  contents: read

env:
  TF_CLI_ARGS_init: -reconfigure -backend=false

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STACK_ID=main" >> $GITHUB_OUTPUT
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "STACK_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}
      environment: ${{ steps.set_variables.outputs.environment }}

  default:
    name: terraform
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      # NOTE:
      # - ci-branch      has ci-branch ENVIRONMENT
      # - ci-branch_plan has ci-branch ENVIRONMENT as well
      environment: ${{ needs.setup.outputs.environment }}_plan
      TF_CLI_ARGS_init: ${{ vars.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
