name: "Test actions/validate"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Apparently terraform init does NOT create a lock.
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  GITHUB_TOKEN: ${{ github.token }}
  TF_CLI_ARGS_init: -reconfigure

jobs:
  default:
    name: terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          backend_override: true

      - uses: ./.github/actions/validate

  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - azurerm/some-rg
          - azurerm/advanced-rg

    name: terraform -chdir=.../${{ matrix.project }} validate
    env:
      TF_DIR: ./assets/terra/${{ matrix.project }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/init
        with:
          working-directory: ${{ env.TF_DIR }}

      - uses: ./.github/actions/validate
        with:
          working-directory: ${{ env.TF_DIR }}
