name: terraform test

on:
  workflow_call: # SRC: https://docs.github.com/en/actions/using-workflows/reusing-workflows
    inputs:
      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      backend_override:
        description: backend_override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: ""

  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
    inputs:
      working-directory:
        description: -chdir
        type: string
        required: false
        default: ./terra

      backend_override:
        description: backend_override.tf
        type: boolean
        required: false
        default: false

      TF_CLI_ARGS_init:
        description: TF_CLI_ARGS_init
        type: string
        required: false
        default: ""

env:
  TF_IN_AUTOMATION: true

jobs:
  validate:
    name: test
    runs-on: ubuntu-latest
    env:
      TF_CLI_ARGS_init: ${{ inputs.TF_CLI_ARGS_init }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
        # with: TODO

      - uses: percebus/github-actions-terraform/.github/actions/setup@main

      - uses: percebus/github-actions-terraform/.github/actions/fmt-check@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/init@main
        with:
          working-directory: ${{ inputs.working-directory }}
          backend_override: ${{ inputs.backend_override }}

      - uses: percebus/github-actions-terraform/.github/actions/validate@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-terraform/.github/actions/test@main
        with:
          working-directory: ${{ inputs.working-directory }}

      - uses: percebus/github-actions-testing/.github/actions/junit@main
        with:
          files_pattern: ${{ inputs.working-directory }}/**/*.xml
          # test-reporter inputs
          reporter: jest-junit
          tests_name: terraform test
          list-suites: all
          list-tests: failed
          # test-summary inputs
          summary_title: "`terraform test` Summary"
          # publish-test-deltas inputs
          publish-test-deltas: true
          comment_title: "`terraform test` Deltas"
          check_name: "`terraform test` Deltas"
