name: "Test actions/init"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    name: terraform init
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init

  terraform_init_options__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform_init_options:
          # - "-input=false -upgrade" # default case already tested in "default" job
          - "-input=false"
          - "-input=false -backend=false"

    name: terraform init ${{ matrix.terraform_init_options }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          terraform_init_options: ${{ matrix.terraform_init_options }}

  TF_CLI_ARGS_init__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_init:
          - "-backend=false"

    name: terraform init ${{ matrix.TF_CLI_ARGS_init }}
    env:
      # NOTE: case is important here
      TF_CLI_ARGS_init: ${{ matrix.TF_CLI_ARGS_init }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init

  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - azurerm/some-rg

    name: terraform init -chdir=${{ matrix.project }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/init
        with:
          working-directory: ./assets/terra/${{ matrix.project }}
