name: "Test actions/fmt-check"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # NOTE: Apparently terraform init does NOT create a lock.
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    name: terraform fmt -check
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/fmt-check

  TF_CLI_ARGS_fmt__inputs_matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_fmt:
          # - "-recursive -diff -list=true" # default case already tested in "default" job
          - "-diff"
          - "-list=false"

    name: terraform fmt -check ${{ matrix.TF_CLI_ARGS_fmt }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/fmt-check
        with:
          TF_CLI_ARGS_fmt: ${{ matrix.TF_CLI_ARGS_fmt }}

  TF_CLI_ARGS_fmt__env_matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_fmt:
          - "-no-color"

    name: "terraform fmt -check (env: ${{ matrix.TF_CLI_ARGS_fmt }})"
    env:
      # NOTE: case is important here
      TF_CLI_ARGS_fmt: ${{ matrix.TF_CLI_ARGS_fmt }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/fmt-check

  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          # - ./terra # already tested by default
          - ./assets/terra

    name: terraform -chdir=${{ matrix.path }} fmt -check
    env:
      TF_DIR: ${{ matrix.path }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/fmt-check
        with:
          working-directory: ${{ env.TF_DIR }}
