name: "Test worfklows/test"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Apparently terraform init does NOT create a lock.
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

# SRC: https://github.com/EnricoMi/publish-unit-test-result-action?tab=readme-ov-file#permissions
# SRC: https://github.com/dorny/test-reporter?tab=readme-ov-file#recommended-setup-for-public-repositories
permissions:
  contents: read
  actions: read
  checks: write
  pull-requests: write

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "TF_CLI_ARGS_init=-reconfigure" >> $GITHUB_OUTPUT
    outputs:
      TF_CLI_ARGS_init: ${{ steps.set_variables.outputs.TF_CLI_ARGS_init }}

  default:
    name: terraform
    needs: setup
    uses: ./.github/workflows/test.yml
    with:
      backend_override: true
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
