name: "Test actions/apply"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  environment: ${{ github.ref_name == 'main' && 'ci_main_plan' || 'ci_branch_plan' }}
  TF_CLI_ARGS_apply: "-dry-run -auto-approve -var-file=./env/${{ vars.ENVIRONMENT }}.tfvars"

jobs:
  default:
    name: terraform apply
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}
    env:
      TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
      - uses: ./.github/actions/apply
        with:
          TF_CLI_ARGS_apply: ""

  apply_plan:
    name: terraform apply tfplan
    runs-on: ubuntu-latest
    environment: ${{ env.environment }}
    env:
      TF_CLI_ARGS_plan: "-var-file=./env/${{ vars.ENVIRONMENT }}.tfvars"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
      - uses: ./.github/actions/plan
      - uses: ./.github/actions/apply
        with:
          TF_CLI_ARGS_apply: ""
