name: "Test actions/init"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # NOTE: Apparently terraform init does NOT create a lock.
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  default:
    name: terraform init
    runs-on: ubuntu-latest
    env:
      TF_CLI_ARGS_init: -reconfigure -backend=false
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init

  TF_CLI_ARGS_init__inputs_matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_init:
          # - "-input=false" # default case already tested in "default" job
          - "-input=false -upgrade"
          - "-input=false -backend=false"

    name: terraform init ${{ matrix.TF_CLI_ARGS_init }}
    env:
      TF_CLI_ARGS_init: -reconfigure -backend=false
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init
        with:
          TF_CLI_ARGS_init: ${{ matrix.TF_CLI_ARGS_init }}

  TF_CLI_ARGS_init__env_matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        TF_CLI_ARGS_init:
          - "-reconfigure -backend=false"
          # - TODO something else

    env:
      # NOTE: case is important here
      TF_CLI_ARGS_init: ${{ matrix.TF_CLI_ARGS_init }}
    name: "terraform init (env: ${{ matrix.TF_CLI_ARGS_init }})"
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init

  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - azurerm/some-rg
          - azurerm/advanced-rg

    name: terraform -chdir=.../${{ matrix.project }} init
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/init
        with:
          working-directory: ./assets/terra/${{ matrix.project }}
