name: "Test worfklows/plan-destroy"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:

concurrency:
  # NOTE: Cancelling an apply might corrupt the state.
  group: ${{ github.ref }}-default
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STACK_ID=main" >> $GITHUB_OUTPUT
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "STACK_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}
      environment: ${{ steps.set_variables.outputs.environment }}

  terraform_plan:
    name: terraform
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}_plan
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}


  terraform_apply_plan:
    name: terraform
    needs:
      - terraform_plan
      - setup
    uses: ./.github/workflows/apply.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  terraform_plan-destroy:
    name: terraform
    needs:
      - terraform_apply_plan
      - setup
    uses: ./.github/workflows/plan-destroy.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}_plan
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
