name: "Test worfklows/validate"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  # NOTE: Apparently terraform init does NOT create a lock.
  cancel-in-progress: true

permissions:
  contents: read

env:
  TF_CLI_ARGS_init: -reconfigure -backend=false

jobs:
  default:
    name: terraform
    uses: ./.github/workflows/validate.yml
    with:
      TF_CLI_ARGS_init: ${{ vars.TF_CLI_ARGS_init }}

  working-directory__matrix:
    needs: default

    strategy:
      matrix:
        project:
          - azurerm/some-rg
          - azurerm/advanced-rg

    name: terraform -chdir=.../${{ matrix.project }}
    uses: ./.github/workflows/validate.yml
    with:
      working-directory: ./assets/terra/${{ matrix.project }}
      TF_CLI_ARGS_init: ${{ vars.TF_CLI_ARGS_init }}
