name: "Test actions/validate"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  REPOSITORY_NAME: ${GITHUB_REPOSITORY#*/}

jobs:
  default:
    name: terraform validate
    runs-on: ubuntu-latest
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup
      - uses: ./.github/actions/init

      - name: variables.ba.sh
        run: bash ./terra/variables.ba.sh

      - uses: ./.github/actions/validate

  working-directory__matrix:
    needs: default
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - azurerm/some-rg

    name: terraform validate -chdir=.../${{ matrix.project }}
    env:
      TF_DIR: ./assets/terra/${{ matrix.project }}
    steps:
      - uses: percebus/github-actions-common/.github/actions/checkout@main
      - uses: ./.github/actions/setup

      - uses: ./.github/actions/init
        with:
          working-directory: ${{ env.TF_DIR }}

      - uses: ./.github/actions/fmt-check
        with:
          working-directory: ${{ env.TF_DIR }}

      - name: variables.ba.sh
        run: bash ${{ env.TF_DIR }}/variables.ba.sh

      - uses: ./.github/actions/validate
        with:
          working-directory: ${{ env.TF_DIR }}
