name: "Test worfklows/apply"

on:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  pull_request:
  push:
    branches:
      - main

concurrency:
  # NOTE: Cancelling an apply might corrupt the state.
  group: ${{ github.ref }}-default-${{ inputs.environment }}
  cancel-in-progress: false

permissions:
  contents: read
  actions: read
  pull-requests: write

jobs:
  setup:
    name: setup
    runs-on: ubuntu-latest
    steps:
      - name: GITHUB_OUTPUT
        id: set_variables
        run: |
          echo "TF_CLI_ARGS_init=-reconfigure" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "STACK_ID=main" >> $GITHUB_OUTPUT
            echo "environment=ci-main" >> $GITHUB_OUTPUT
          else
            echo "STACK_ID=pr-${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
            echo "environment=ci-branch" >> $GITHUB_OUTPUT
          fi
    outputs:
      STACK_ID: ${{ steps.set_variables.outputs.STACK_ID }}
      environment: ${{ steps.set_variables.outputs.environment }}
      TF_CLI_ARGS_init: ${{ steps.set_variables.outputs.TF_CLI_ARGS_init }}

  terraform_plan:
    name: terraform
    needs: setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}_plan
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
      TF_CLI_ARGS_plan: "-var STACK_ID=${{ needs.setup.outputs.STACK_ID }}"
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  terraform_apply_plan:
    name: terraform
    needs:
      - terraform_plan
      - setup
    uses: ./.github/workflows/apply.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}
      TF_CLI_ARGS_init: ${{ needs.setup.outputs.TF_CLI_ARGS_init }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  terraform_plan-destroy:
    name: terraform
    needs:
      - terraform_apply_plan
      - setup
    uses: ./.github/workflows/plan.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}_plan
      destroy: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}

  terraform_apply-destroy:
    name: terraform
    needs:
      - terraform_plan-destroy
      - setup
    uses: ./.github/workflows/apply.yml
    with:
      environment: ${{ needs.setup.outputs.environment }}
      destroy: true
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
